# Meta Data for SEO

## Homepage
title = "Dekart"
titleSeparator = "-"
titleAddition = "Maps for your Data Platform"
description = "Open-source WebGL-powered map visualization and spatial analytics for modern data warehouses."

## Open Graph + Twitter Cards
images = ["dekart-social-preview-0-12.png"]
twitterCreator = "delfrrr"
ogLocale = "en_US"

## JSON-LD
# schemaType = "Organization"
schemaLogo = "dekart-logo.png"
# schemaTwitter = "http://twitter.com/delfrrr"
# schemaLinkedIn = "https://www.linkedin.com/in/bilonenko/"
schemaGitHub = "https://github.com/dekart-xyz/dekart"
schemaSection = "blog"

## Sitelinks Search Box
siteLinksSearchBox = false

## Chrome Browser
themeColor = "#fff"

# Images
quality = 100
bgColor = "#fff"
landscapePhotoWidths = [2048, 1600, 1024, 512]
portraitPhotoWidths = [2048, 1600, 1024, 512]
lqipWidth = "20x"

# Alert
alert = false
alertText = "Using Dekart? <a class=\"alert-link\" href=\"https://github.com/dekart-xyz/dekart/stargazers\">Help us 🩷</a></a>"

# Edit Page
docsRepo = "https://github.com/dekart-xyz/www"
editPage = true
